export const UM_ME_URL = 'nurse:// me' // 我的界面tab
export const UM_EL_URL = 'nurse:// el' // 学习界面tab
export const UM_JOB_URL = 'nurse:// job' // 招聘tab
export const UM_INFO_URL = 'nurse:// information' // 资讯tab
export const UM_PROFILE_URL = 'nurse:// profile' // 编辑个人信息
export const UM_SETTING_URL = 'nurse:// setting' // 设置
export const UM_MODPWD_URL = 'nurse:// modifypwd' // 修改密码
export const UM_FEEDBACK_URL = 'nurse:// feedback' //  反馈意见
export const UM_ABOUTUS_URL = 'nurse:// aboutus' // 关于我们 兼职tab
export const UM_PTJ_INFO = 'nurse:// ptinformation' // 兼职任务发布
export const UM_PTJ_QUA = 'nurse:// qualication' // 兼职广场 兼职认证通过
export const UM_PTJ_UNQUA = 'nurse:// unqualication' // 兼职认证不通过
export const UM_PTJ_UNPASS = 'nurse:// unpass' // 兼职订单审核不通过
export const UM_PTJ_PASS = 'nurse:// pass' // 兼职订单审核通过
export const UM_PTJ_CLOSE = 'nurse:// orderclose' // 待服务兼职订单手动关闭
export const UM_MSG_CENTER = 'nurse:// message_center' // 消息中心
export const UM_GRANT_CERTIFICATE = 'nurse:// grantcertificate' // 电子证书详情
export const UM_CF_UNPASS = 'nurse:// certificateunpass' // 证书认证审核不通过
export const UM_CF_PASS = 'nurse:// certificatepass' // 证书认证审核通过
export const UM_CERTIFICATE = 'nurse:// certificate' // 我的证书
export const UM_SKILLS = 'nurse:// skills' // 我的技能
export const UM_CP = 'nurse:// cp' // 测评
export const UM_INFORMATION_ID = 'nurse:// information' // 资讯详情
export const UM_EL_DETAIL = 'nurse:// el_detail' // 学习课程详情
export const UM_EL_LIST = 'nurse:// el_list' // 学习课程包列表
export const UM_JOB_DETAIL = 'nurse:// job_detail' // 招聘任务详情
export const UM_JOB_LIST = 'nurse:// job_list' // 招聘专题列表
export const UM_MAIN = 'nurse:// main'
export const UM_JOB_DELIVERY = 'nurse:// my_delivery' // 招聘我的投递
export const UM_JOB_RESUME = 'nurse:// my_resume' // 招聘我的简历
export const UM_SUBMAJOR = 'nurse:// submajor' // 亚专业选择
export const UM_CARD = 'nurse:// card' // 我的学习卡
export const UM_UDESK = 'nurse:// udesk' // UDesk客服
export const UM_COMPLETE = 'nurse:// complete' // 完成信息
export const UM_THIRD_PATH = 'nurse:// third_path' // 跳转第三方网址
export const UM_SKILL_DETAIL = 'nurse:// skill_detaill' // 技能详情
